foreman/config/routes.rb
Foreman::Application.routes.draw do
  apipie_dsl
  resources :mail_notifications, only: [] do
    collection do
      get 'auto_complete_search'
    end
  end

  resources :config_reports, only: [:index, :show, :destroy] do
    collection do
      get 'auto_complete_search'
    end
  end

  welcoming_controllers = [
    'architectures',
    'auth_source_ldaps',
    'bookmarks',
    'common_parameters',
    'compute_profiles',
    'compute_resources',
    'config_reports',
    'domains',
    'fact_values',
    'hostgroups',
    'hosts',
    'http_proxies',
    'media',
    'models',
    'operatingsystems',
    'provisioning_templates',
    'ptables',
    'realms',
    'report_templates',
    'smart_proxies',
    'subnets',
    'usergroups',
  ]

  welcoming_controllers.each do |welcoming_controller|
    get "#{welcoming_controller}/help", action: :welcome, controller: welcoming_controller
  end

  constraints(id: /[^\/]+/) do
    resources :hosts do
      member do
        get 'clone'
        get 'review_before_build'
        put 'setBuild'
        get 'cancelBuild'
        get 'build_errors'
        get 'pxe_config'
        put 'toggle_manage'
        put 'power'
        get 'console'
        get 'overview'
        get 'bmc'
        get 'vm'
        get 'runtime'
        get 'resources'
        get 'templates'
        get 'nics'
        post 'forget_status'
        get 'statuses'
        put 'ipmi_boot'
        put 'disassociate'
      end
      collection do
        post 'multiple_actions'
        post 'multiple_parameters'
        post 'update_multiple_parameters'
        post 'select_multiple_hostgroup'
        post 'update_multiple_hostgroup'
        post 'select_multiple_owner'
        post 'update_multiple_owner'
        post 'select_multiple_power_state'
        post 'update_multiple_power_state'
        post 'select_multiple_puppet_ca_proxy'
        post 'update_multiple_puppet_ca_proxy'
        post 'multiple_destroy'
        post 'submit_multiple_destroy'
        post 'multiple_build'
        post 'submit_multiple_build'
        get 'reset_multiple'
        post 'multiple_disable'
        post 'submit_multiple_disable'
        post 'multiple_enable'
        post 'submit_multiple_enable'
        post 'multiple_disassociate'
        post 'update_multiple_disassociate'
        get 'auto_complete_search'
        post 'template_used'
        get 'active'
        get 'pending'
        get 'out_of_sync'
        get 'errors'
        get 'disabled'
        post 'current_parameters'
        post 'process_hostgroup'
        post 'process_taxonomy'
        post 'architecture_selected'
        post 'os_selected'
        post 'domain_selected'
        post 'use_image_selected'
        post 'compute_resource_selected'
        post 'scheduler_hint_selected'
        post 'interfaces'
        post 'medium_selected'
        post 'select_multiple_organization'
        post 'update_multiple_organization'
        post 'select_multiple_location'
        post 'update_multiple_location'
        post 'rebuild_config'
        post 'submit_rebuild_config'
        get 'random_name', only: :new
        get 'preview_host_collection'

        get 'register' => 'react#index'
        post 'register', to: 'registration_commands#create'
        get 'register/data', to: 'registration_commands#form_data'
        get 'register/os/:id', to: 'registration_commands#operatingsystem_template'
      end

      constraints(host_id: /[^\/]+/) do
        resources :config_reports, only: [:index, :show]
        resources :facts, only: :index, controller: :fact_values

        get 'parent_facts/*parent_fact/facts', to: 'fact_values#index', as: 'parent_fact_facts', parent_fact: /[\/\w.:_-]+/
      end
    end

    resources :bookmarks, except: [:show, :new, :create] do
      collection do
        get 'auto_complete_search'
      end
    end

    get 'parent_facts/:parent_fact/facts', to: 'fact_values#index', as: 'parent_fact_facts'
    resources :facts, only: [:index, :show] do
      constraints(id: /[^\/]+/) do
        resources :values, only: :index, controller: :fact_values, as: "host_fact_values"
      end
    end

    get 'unattended/template/:id/*hostgroup', to: "unattended#hostgroup_template", hostgroup: /.+/, format: 'text'
  end

  resources :settings, only: [:index, :update] do
    collection do
      get 'auto_complete_search'
    end
  end
  resources :common_parameters, except: [:show] do
    collection do
      get 'auto_complete_search'
    end
  end
  resources :parameters, only: [:index] do
    collection do
      get 'auto_complete_search'
    end
  end

  resources :compute_profiles do
    collection do
      get 'auto_complete_search'
    end
    resources :compute_attributes, only: [:create, :edit, :update]
    resources :compute_resources, only: [] do
      resources :compute_attributes, only: :new
    end
  end

  resources :hostgroups, except: [:show] do
    member do
      get 'nest'
      get 'clone'
    end
    collection do
      get 'auto_complete_search'
      post 'architecture_selected'
      post 'os_selected'
      post 'domain_selected'
      post 'use_image_selected'
      post 'medium_selected'
      post 'process_hostgroup'
    end
  end

  resources :smart_proxies do
    member do
      get 'ping'
      put 'refresh'
      get 'version'
      get 'plugin_version'
      get 'tftp_server'
      get 'log_pane'
      get 'failed_modules'
      get 'errors_card'
      get 'modules_card'
      post 'expire_logs'
    end
    constraints(id: /[^\/]+/) do
      resources :puppetca, only: [:index, :update, :destroy] do
        member do
          get 'counts'
          get 'expiry'
        end
      end
      resources :autosign, only: [:index, :new, :create, :destroy] do
        member do
          get 'counts'
        end
      end
    end
    collection do
      get 'auto_complete_search'
    end
  end

  resources :http_proxies, controller: 'http_proxies' do
    collection do
      get 'auto_complete_search'
      put 'test_connection'
    end
  end

  resources :fact_values, only: [:index] do
    collection do
      get 'auto_complete_search'
    end
  end

  resources :audits, only: [:index], constraints: ->(req) { req.format == :json }
  match '/audits/auto_complete_search' => 'audits#auto_complete_search', :via => [:get]
  match '/audits' => 'react#index', :via => [:get]

  resources :usergroups, except: [:show] do
    collection do
      get 'auto_complete_search'
    end
  end

  get 'menu', to: 'user_menus#menu'

  resources :users, except: [:show] do
    collection do
      get 'login'
      post 'login'
      get 'logout'
      post 'logout'
      get 'extlogin'
      get 'extlogout'
      get 'auto_complete_search'
      delete 'stop_impersonation'
    end
    member do
      post 'impersonate'
    end
    resources :ssh_keys, only: [:new, :create, :destroy]
  end
  resources :roles, except: [:show] do
    member do
      get 'clone'
      patch 'disable_filters_overriding'
    end
    collection do
      get 'auto_complete_search'
    end
  end

  resources :filters, except: [:show] do
    member do
      patch 'disable_overriding'
    end
    collection do
      get 'auto_complete_search'
    end
  end

  resources :permissions, only: [:index]

  resources :auth_source_ldaps, except: [:show, :index] do
    collection do
      put 'test_connection'
    end
  end

  resources :auth_sources, only: [:show, :index]
  resources :auth_source_externals, only: [:update, :edit]

  put 'users/(:id)/test_mail', to: 'users#test_mail', as: 'test_mail_user'

  constraints(id: /[^\/]+/) do
    resources :external_usergroups, except: [:index, :new, :create, :show, :edit, :update, :destroy] do
      member do
        put 'refresh'
      end
    end
  end

  scope 'templates' do
    resources :report_templates, except: [:show] do
      member do
        get 'clone_template'
        get 'lock'
        get 'unlock'
        get 'export'
        get 'generate'
        post 'schedule_report'
        post 'preview'
        get 'report_data'
      end
      collection do
        post 'preview'
        get 'revision'
        get 'auto_complete_search'
      end
    end
  end

  if SETTINGS[:unattended]
    resources :provisioning_templates, only: [] do
      collection do
        get 'build_pxe_default'
      end
    end

    scope 'templates' do
      resources :ptables, except: [:show] do
        member do
          get 'clone_template'
          get 'lock'
          get 'unlock'
          get 'export'
          post 'preview'
        end
        collection do
          post 'preview'
          get 'revision'
          get 'auto_complete_search'
        end
      end

      resources :provisioning_templates, except: [:show] do
        member do
          get 'clone_template'
          get 'lock'
          get 'unlock'
          get 'export'
          post 'preview'
        end
        collection do
          post 'preview'
          get 'revision'
          get 'auto_complete_search'
        end
      end
    end

    constraints(id: /[^\/]+/) do
      resources :domains, except: [:show] do
        collection do
          get 'auto_complete_search'
        end
      end

      resources :operatingsystems, except: [:show] do
        member do
          get 'bootfiles'
          get 'clone'
        end
        collection do
          get 'auto_complete_search'
        end
      end
    end
    resources :media, except: [:show] do
      collection do
        get 'auto_complete_search'
      end
    end

    resources :models, except: [:show, :index] do
      collection do
        get 'auto_complete_search'
      end
    end
    match 'models' => 'react#index', :via => :get

    resources :architectures, except: [:show] do
      collection do
        get 'auto_complete_search'
      end
    end

    constraints(id: /[^\/]+/) do
      resources :compute_resources do
        member do
          post 'template_selected'

foreman/app/models/parameters/common_parameter.rb
class CommonParameter < Parameter
  audited :except => [:priority, :searchable_value]
  validates :name, :uniqueness => true

  def associated_type
    N_('global')
  end
end

foreman/app/controllers/api/v2/common_parameters_controller.rb
module Api
  module V2
    class CommonParametersController < V2::BaseController
      include Foreman::Controller::Parameters::Parameter

      before_action :find_resource, :only => %w{show update destroy}

      api :GET, "/common_parameters/", N_("List all global parameters")
      param :show_hidden, :bool, :desc => N_("Display hidden values")
      param_group :search_and_pagination, ::Api::V2::BaseController
      add_scoped_search_description_for(Parameter)

      def index
        @common_parameters = resource_scope_for_index(:permission => :view_params)
      end

      api :GET, "/common_parameters/:id/", N_("Show a global parameter")
      param :show_hidden, :bool, :desc => N_("Display hidden values")
      param :id, :identifier, :required => true

      def show
      end

      def_param_group :common_parameter do
        param :common_parameter, Hash, :required => true, :action_aware => true do
          param :name, String, :required => true
          param :value, String, :required => true
          param :parameter_type, Parameter::KEY_TYPES, :desc => N_("Type of value"), :required => true
          param :hidden_value, [true, false]
        end
      end

      api :POST, "/common_parameters/", N_("Create a global parameter")
      param_group :common_parameter, :as => :create

      def create
        @common_parameter = CommonParameter.new(parameter_params(::CommonParameter))
        process_response @common_parameter.save
      end

      api :PUT, "/common_parameters/:id/", N_("Update a global parameter")
      param :id, :identifier, :required => true
      param_group :common_parameter

      def update
        process_response @common_parameter.update(parameter_params(::CommonParameter))
      end

      api :DELETE, "/common_parameters/:id/", N_("Delete a global parameter")
      param :id, :identifier, :required => true

      def destroy
        process_response @common_parameter.destroy
      end

      private

      def controller_permission
        'params'
      end

      def resource_scope(*args, &block)
        super.where(:type => 'CommonParameter')
      end

      def resource_class
        Parameter
      end
    end
  end
end

foreman/app/controllers/common_parameters_controller.rb
class CommonParametersController < ApplicationController
  include Foreman::Controller::AutoCompleteSearch
  include Foreman::Controller::Parameters::Parameter

  before_action :find_resource, :only => [:edit, :update, :destroy]

  def index
    @common_parameters = resource_base_search_and_page
  end

  def new
    @common_parameter = CommonParameter.new
  end

  def create
    @common_parameter = CommonParameter.new(parameter_params(::CommonParameter))
    if @common_parameter.save
      process_success
    else
      process_error
    end
  end

  def edit
  end

  def update
    if @common_parameter.update(parameter_params(::CommonParameter))
      process_success
    else
      process_error
    end
  end

  def destroy
    if @common_parameter.destroy
      process_success
    else
      process_error
    end
  end

  private

  def controller_permission
    'params'
  end

  def resource_base
    model_of_controller.authorized(current_permission, Parameter).where(:type => 'CommonParameter')
  end
end

foreman/app/helpers/common_parameters_helper.rb
module CommonParametersHelper
  # Return true if user is authorized for controller/action OR controller/action@type, otherwise false
  # third argument may be specific object (usually for edit and destroy actions)
  def authorized_via_my_scope(controller, action, object = nil)
    authorized_for(:controller => controller, :action => action, :auth_object => object)
  end

  def parameters_title
    _("Parameters that would be associated with hosts in this %s") % type
  end

  def parameter_value_field(value)
    source_name = value[:source_name] ? "(#{value[:source_name]})" : nil
    popover_tag = popover('', _("<b>Source:</b> %{type} %{name}") % { :type => _(value[:source]), :name => html_escape(source_name) }, :data => { :placement => 'top' })
    content_tag(
      :div,
      parameter_value_content(
        "value_#{value[:safe_value]}",
        Parameter.format_value_before_type_cast(value[:safe_value], value[:parameter_type]),
        :hidden_value? => value[:hidden_value?],
        :popover => popover_tag, :disabled => true
      ) + fullscreen_input,
      :class => 'input-group'
    )
  end

  def parameter_value_content(id, value, options)
    content_tag(:span, options[:popover], :class => "input-group-addon") + lookup_key_field(id, value, options)
  end

  def omit_help
    popover(nil, omit_help_body, :title => omit_help_title)
  end

  def omit_help_title
    _("Omit parameter from classification")
  end

  def omit_help_body
    _("Foreman will not send this parameter in classification output.")
  end

  def hidden_value_field(f, field, disabled, options = {})
    hidden = options.delete(:hidden_value) || f.object.hidden_value?
    html_class = "form-control no-stretch"
    html_class += " masked-input" if hidden

    input = f.text_area(field, options.merge(:disabled => disabled,
                                             :class => html_class,
                                             :rows => 1,
                                             :id => dom_id(f.object) + '_value',
                                             :placeholder => _("Value"),
                                             :value => f.object.value_before_type_cast))

    input_group(input, input_group_btn(hidden_toggle(f.object.hidden_value?), fullscreen_button("$(this).closest('.input-group').find('input,textarea')")))
  end

  def lookup_key_field(id, value, options)
    option_hash = { :rows => 1,
                    :class => 'form-control no-stretch',
                    :'data-property' => 'value',
                    :'data-hidden-value' => LookupKey.hidden_value,
                    :'data-inherited-value' => options[:inherited_value],
                    :name => options[:name].to_s,
                    :disabled => options[:disabled] }
    option_hash[:class] += " masked-input" if options[:hidden_value?]

    case options[:lookup_key_type]
    when "boolean"
      select_tag(id, options_for_select(['true', 'false'], value), option_hash)
    when "integer", "real"
      number_field_tag(id, value, option_hash)
    else
      text_area_tag(id, value, option_hash)
    end
  end

  def authorized_resource_parameters(params_authorizer, parameters_by_type)
    parameter_ids_to_view = find_parameters_to_view(params_authorizer, parameters_by_type).map(&:id)
    resource_parameters = parameters_by_type.select { |p| parameter_ids_to_view.include?(p.id) }
    resource_parameters += parameters_by_type.select(&:new_record?)
    resource_parameters
  end

  def find_parameters_to_view(params_authorizer, parameters_by_type, user = User.current)
    return parameters_by_type.none if user.nil?
    return parameters_by_type.all if user.admin?
    params_authorizer.find_collection(parameters_by_type.klass, :permission => :view_params)
  end

  def can_create_parameter?(params_authorizer)
    @can_create_param ||= params_authorizer.can?(:create_params)
  end
end

foreman/app/views/common_parameters/_form.html.erb
<%= form_for @common_parameter do |f| %>
    <%= base_errors_for @common_parameter %>
    <%= text_f f, :name %>
    <%= param_type_selector(f) %>
    <%= textarea_f f, :value, :value => f.object.value_before_type_cast, :size => "col-md-8",
                   :rows => line_count(f, :value),
                   :input_group_btn => fullscreen_input,
                   :class => "form-control no-stretch #{'masked-input' if @common_parameter.hidden_value?}" %>
    <%= checkbox_f f, :hidden_value, :class => 'hidden_value_textarea_switch', :onchange => 'turn_textarea_switch()', :checked => f.object.hidden_value? %>

   <input type="hidden" id="old" value="<%= @common_parameter.value %>" />
   <input type="hidden" id="new" value="<%= @common_parameter.value %>" />

   <%= submit_or_cancel f %>
<% end %>

foreman/app/views/common_parameters/_inherited_parameters.html.erb
<table class="table table-fixed" id="inherited_parameters">
  <thead class="white-header">
    <tr>
      <th class='col-md-3'><%= _("Name") %></th>
      <th class='col-md-2'><%= _('Type') %></th>
      <th class='col-md-6'><%= _("Value") %></th>
      <th class='col-md-1 ca'><%= _('Actions') %></th>
    </tr>
  </thead>
  <% if inherited_parameters.present? %>
    <tbody>
      <% keys = inherited_parameters.keys.sort %>
      <% keys.each do |name| %>
        <% overriden = parameters.detect{|param| param.name == name}.present?
           param_obj = inherited_parameters[name]
        %>
        <tr class="<%="override-param" if overriden %>">
          <td class="ellipsis"><%= content_tag :span, name, :id => "name_#{name}"%>
          </td>
          <td class="ellipsis"><%= content_tag :span, param_obj[:parameter_type], :id => "parameter_type_#{param_obj[:parameter_type]}"%>
          </td>
          <td><%= parameter_value_field param_obj %></td>
          <td>
            <%= link_to_function(_("Override"), "override_param(this)", :title => _("Override this value"),
                                 :'data-tag' => 'override', :class => "btn btn-default", :id => "override-param-#{name}") if authorized_via_my_scope("host_editing", "create_params") %>
          </td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>

foreman/app/views/common_parameters/_parameter.html.erb
<tr class="fields <%= 'has-error' if f.object.errors.any? %>" id="<%= dom_id(f.object) + '_row' %>">
  <% authorized = f.object.new_record? ? can_create_parameter?(params_authorizer) : params_authorizer.can?(:edit_params, f.object) %>
  <td>
    <%= f.text_field(:name,  :class => "form-control", :disabled => !authorized, :placeholder => _("Name")) %>
  </td>
  <td><%= param_type_selector(f, true) %></td>
  <td>
    <%= hidden_value_field(f, :value, !authorized) %>
  </td>
  <td>
    <%= f.check_box(:hidden_value, :class => 'set_hidden_value hide', :checked => f.object.hidden_value?) if authorized %>
    <%= link_to_remove_fields(_('Remove'), f) if f.object.new_record? || params_authorizer.can?(:destroy_params, f.object) %>
  </td>
</tr>
<% if f.object.errors.any? %>
  <tr class="error-msg-block has-error">
    <td colspan="3">
      <span class="help-block">
        <%= f.object.errors.full_messages.to_sentence %>
      </span>
    </td>
  </tr>
<% end %>

foreman/app/views/common_parameters/_parameters.html.erb
<%
  parameters_by_type = f.object.send(type)
  params_authorizer = Authorizer.new(User.current, :collection => parameters_by_type)
%>
<div id="parameters">
  <%= authorized_via_my_scope("host_editing", "create_params") ? link_to_add_fields('+ ' + _("Add Parameter"), f, type, "common_parameters/parameter", { :target => '#global_parameters_table tbody', :direction => 'prepend', :locals => { :params_authorizer => params_authorizer }}) : "" %>
  <table class="table" id="global_parameters_table">
    <thead class="white-header">
    <tr>
      <th class='col-md-3'><%= _("Name") %></th>
      <th class='col-md-2'><%= _('Type') %></th>
      <th class='col-md-6'><%= _("Value") %></th>
      <th class='col-md-1 ca'><%= _('Actions') %></th>
    </tr>
    </thead>
    <tbody>
      <% authorized_resource_parameters(params_authorizer, parameters_by_type).each do |parameter| %>
        <%= f.fields_for type, parameter do |builder| %>
          <%= render "common_parameters/parameter", :f => builder, :params_authorizer => params_authorizer %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

foreman/app/views/common_parameters/_show_parameter.html.erb
<ul>
  <% parameter.each do |p| %>
    <li><%= "#{p.name} #{p.value}" %></li>
  <% end %>
</ul>

foreman/app/views/common_parameters/edit.html.erb
<% title _("Edit %s") % @common_parameter.to_s  %>

<%= render :partial => 'form' %>

foreman/app/views/common_parameters/index.html.erb
<% title _("Global Parameters") %>

<% title_actions new_link(_("Create Parameter")),
                 documentation_button('4.2.3Parameters') %>


<table class="<%= table_css_classes('table-hover table-fixed')%>">
  <thead>
    <tr>
      <th class="col-md-3"><%= sort :name, :as => s_("Parameter|Name") %></th>
      <th class="col-md-6" style='min-width: 60%;'><%= sort :value, :as =>  s_("Parameter|Value")%></th>
      <th class="col-md-2"><%= sort :parameter_type, :as =>  s_("Parameter|Type")%></th>
      <th class="col-md-1"><%= _('Actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% for common_parameter in @common_parameters %>
      <tr id="<%= dom_id(common_parameter) %>_row">
        <td class="ellipsis"><%= link_to_if_authorized common_parameter, hash_for_edit_common_parameter_path(:id => common_parameter).merge(:auth_object => common_parameter, :authorizer => authorizer, :permission => 'edit_params') %></td>
        <td class='ellipsis'>
          <%= common_parameter.hidden_value? ? common_parameter.hidden_value : common_parameter.value %>
        </td>
        <td class='ellipsis'><%= common_parameter.parameter_type %></td>
        <td>
          <%= action_buttons(display_delete_if_authorized hash_for_common_parameter_path(:id => common_parameter).merge(:auth_object => common_parameter, :authorizer => authorizer, :permission => 'destroy_params'),
            :data => { :confirm => _("Delete %s?") % common_parameter.name } ) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate_with_info @common_parameters %>

foreman/app/views/common_parameters/new.html.erb
<% title _("Create Global Parameter") %>

<%= render :partial => 'form' %>

foreman/app/views/common_parameters/welcome.html.erb
<% content_for(:title, _("Global Parameters")) %>
<% description = _("Foreman allows to define a hierarchy of parameter inheritance, where global parameters accessible from any manifest.")%>
<% action = { :title => _("Create Global Parameter"), :url => new_common_parameter_path } if authorized_for(:action => :new)%>
<%= react_component('EmptyState', {
                                    :icon => 'list-ul',
                                    :iconType => 'fa',
                                    :header => _('Global Parameters'),
                                    :description => description,
                                    :documentation => { :url => documentation_url("global-parameters") },
                                    :action => action
                                  }) %>