foreman/config/routes.rb
Foreman::Application.routes.draw do
  apipie_dsl
  resources :mail_notifications, only: [] do
    collection do
      get 'auto_complete_search'
    end
  end

  resources :config_reports, only: [:index, :show, :destroy] do
    collection do
      get 'auto_complete_search'
    end
  end

  welcoming_controllers = [
    'architectures',
    'auth_source_ldaps',
    'bookmarks',
    'common_parameters',
    'compute_profiles',
    'compute_resources',
    'config_reports',
    'domains',
    'fact_values',
    'hostgroups',
    'hosts',
    'http_proxies',
    'media',
    'models',
    'operatingsystems',
    'provisioning_templates',
    'ptables',
    'realms',
    'report_templates',
    'smart_proxies',
    'subnets',
    'usergroups',
  ]

  welcoming_controllers.each do |welcoming_controller|
    get "#{welcoming_controller}/help", action: :welcome, controller: welcoming_controller
  end

  constraints(id: /[^\/]+/) do
    resources :hosts do
      member do
        get 'clone'
        get 'review_before_build'
        put 'setBuild'
        get 'cancelBuild'
        get 'build_errors'
        get 'pxe_config'
        put 'toggle_manage'
        put 'power'
        get 'console'
        get 'overview'
        get 'bmc'
        get 'vm'
        get 'runtime'
        get 'resources'
        get 'templates'
        get 'nics'
        post 'forget_status'
        get 'statuses'
        put 'ipmi_boot'
        put 'disassociate'
      end
      collection do
        post 'multiple_actions'
        post 'multiple_parameters'
        post 'update_multiple_parameters'
        post 'select_multiple_hostgroup'
        post 'update_multiple_hostgroup'
        post 'select_multiple_owner'
        post 'update_multiple_owner'
        post 'select_multiple_power_state'
        post 'update_multiple_power_state'
        post 'select_multiple_puppet_ca_proxy'
        post 'update_multiple_puppet_ca_proxy'
        post 'multiple_destroy'
        post 'submit_multiple_destroy'
        post 'multiple_build'
        post 'submit_multiple_build'
        get 'reset_multiple'
        post 'multiple_disable'
        post 'submit_multiple_disable'
        post 'multiple_enable'
        post 'submit_multiple_enable'
        post 'multiple_disassociate'
        post 'update_multiple_disassociate'
        get 'auto_complete_search'
        post 'template_used'
        get 'active'
        get 'pending'
        get 'out_of_sync'
        get 'errors'
        get 'disabled'
        post 'current_parameters'
        post 'process_hostgroup'
        post 'process_taxonomy'
        post 'architecture_selected'
        post 'os_selected'
        post 'domain_selected'
        post 'use_image_selected'
        post 'compute_resource_selected'
        post 'scheduler_hint_selected'
        post 'interfaces'
        post 'medium_selected'
        post 'select_multiple_organization'
        post 'update_multiple_organization'
        post 'select_multiple_location'
        post 'update_multiple_location'
        post 'rebuild_config'
        post 'submit_rebuild_config'
        get 'random_name', only: :new
        get 'preview_host_collection'

        get 'register' => 'react#index'
        post 'register', to: 'registration_commands#create'
        get 'register/data', to: 'registration_commands#form_data'
        get 'register/os/:id', to: 'registration_commands#operatingsystem_template'
      end

      constraints(host_id: /[^\/]+/) do
        resources :config_reports, only: [:index, :show]
        resources :facts, only: :index, controller: :fact_values

        get 'parent_facts/*parent_fact/facts', to: 'fact_values#index', as: 'parent_fact_facts', parent_fact: /[\/\w.:_-]+/
      end
    end

    resources :bookmarks, except: [:show, :new, :create] do
      collection do
        get 'auto_complete_search'
      end
    end

    get 'parent_facts/:parent_fact/facts', to: 'fact_values#index', as: 'parent_fact_facts'
    resources :facts, only: [:index, :show] do
      constraints(id: /[^\/]+/) do
        resources :values, only: :index, controller: :fact_values, as: "host_fact_values"
      end
    end

    get 'unattended/template/:id/*hostgroup', to: "unattended#hostgroup_template", hostgroup: /.+/, format: 'text'
  end

  resources :settings, only: [:index, :update] do
    collection do
      get 'auto_complete_search'
    end
  end
  resources :common_parameters, except: [:show] do
    collection do
      get 'auto_complete_search'
    end
  end
  resources :parameters, only: [:index] do
    collection do
      get 'auto_complete_search'
    end
  end

  resources :compute_profiles do
    collection do
      get 'auto_complete_search'
    end
    resources :compute_attributes, only: [:create, :edit, :update]
    resources :compute_resources, only: [] do
      resources :compute_attributes, only: :new
    end
  end

  resources :hostgroups, except: [:show] do
    member do
      get 'nest'
      get 'clone'
    end
    collection do
      get 'auto_complete_search'
      post 'architecture_selected'
      post 'os_selected'
      post 'domain_selected'
      post 'use_image_selected'
      post 'medium_selected'
      post 'process_hostgroup'
    end
  end

  resources :smart_proxies do
    member do
      get 'ping'
      put 'refresh'
      get 'version'
      get 'plugin_version'
      get 'tftp_server'
      get 'log_pane'
      get 'failed_modules'
      get 'errors_card'
      get 'modules_card'
      post 'expire_logs'
    end
    constraints(id: /[^\/]+/) do
      resources :puppetca, only: [:index, :update, :destroy] do
        member do
          get 'counts'
          get 'expiry'
        end
      end
      resources :autosign, only: [:index, :new, :create, :destroy] do
        member do
          get 'counts'
        end
      end
    end
    collection do
      get 'auto_complete_search'
    end
  end

  resources :http_proxies, controller: 'http_proxies' do
    collection do
      get 'auto_complete_search'
      put 'test_connection'
    end
  end

  resources :fact_values, only: [:index] do
    collection do
      get 'auto_complete_search'
    end
  end

  resources :audits, only: [:index], constraints: ->(req) { req.format == :json }
  match '/audits/auto_complete_search' => 'audits#auto_complete_search', :via => [:get]
  match '/audits' => 'react#index', :via => [:get]

  resources :usergroups, except: [:show] do
    collection do
      get 'auto_complete_search'
    end
  end

  get 'menu', to: 'user_menus#menu'

  resources :users, except: [:show] do
    collection do
      get 'login'
      post 'login'
      get 'logout'
      post 'logout'
      get 'extlogin'
      get 'extlogout'
      get 'auto_complete_search'
      delete 'stop_impersonation'
    end
    member do
      post 'impersonate'
    end
    resources :ssh_keys, only: [:new, :create, :destroy]
  end
  resources :roles, except: [:show] do
    member do
      get 'clone'
      patch 'disable_filters_overriding'
    end
    collection do
      get 'auto_complete_search'
    end
  end

  resources :filters, except: [:show] do
    member do
      patch 'disable_overriding'
    end
    collection do
      get 'auto_complete_search'
    end
  end

  resources :permissions, only: [:index]

  resources :auth_source_ldaps, except: [:show, :index] do
    collection do
      put 'test_connection'
    end
  end

  resources :auth_sources, only: [:show, :index]
  resources :auth_source_externals, only: [:update, :edit]

  put 'users/(:id)/test_mail', to: 'users#test_mail', as: 'test_mail_user'

  constraints(id: /[^\/]+/) do
    resources :external_usergroups, except: [:index, :new, :create, :show, :edit, :update, :destroy] do
      member do
        put 'refresh'
      end
    end
  end

  scope 'templates' do
    resources :report_templates, except: [:show] do
      member do
        get 'clone_template'
        get 'lock'
        get 'unlock'
        get 'export'
        get 'generate'
        post 'schedule_report'
        post 'preview'
        get 'report_data'
      end
      collection do
        post 'preview'
        get 'revision'
        get 'auto_complete_search'
      end
    end
  end

  if SETTINGS[:unattended]
    resources :provisioning_templates, only: [] do
      collection do
        get 'build_pxe_default'
      end
    end

    scope 'templates' do
      resources :ptables, except: [:show] do
        member do
          get 'clone_template'
          get 'lock'
          get 'unlock'
          get 'export'
          post 'preview'
        end
        collection do
          post 'preview'
          get 'revision'
          get 'auto_complete_search'
        end
      end

      resources :provisioning_templates, except: [:show] do
        member do
          get 'clone_template'
          get 'lock'
          get 'unlock'
          get 'export'
          post 'preview'
        end
        collection do
          post 'preview'
          get 'revision'
          get 'auto_complete_search'
        end
      end
    end

    constraints(id: /[^\/]+/) do
      resources :domains, except: [:show] do
        collection do
          get 'auto_complete_search'
        end
      end

      resources :operatingsystems, except: [:show] do
        member do
          get 'bootfiles'
          get 'clone'
        end
        collection do
          get 'auto_complete_search'
        end
      end
    end
    resources :media, except: [:show] do
      collection do
        get 'auto_complete_search'
      end
    end

    resources :models, except: [:show, :index] do
      collection do
        get 'auto_complete_search'
      end
    end
    match 'models' => 'react#index', :via => :get

    resources :architectures, except: [:show] do
      collection do
        get 'auto_complete_search'
      end
    end

    constraints(id: /[^\/]+/) do
      resources :compute_resources do
        member do
          post 'template_selected'

foreman/app/controllers/concerns/foreman/controller/parameters/compute_resource.rb
module Foreman::Controller::Parameters::ComputeResource
  extend ActiveSupport::Concern
  include Foreman::Controller::Parameters::Taxonomix

  class_methods do
    def compute_resource_params_filter
      Foreman::ParameterFilter.new(::ComputeResource).tap do |filter|
        filter.permit :description,
          :display_type,
          :name,
          :password,
          :provider,
          :set_console_password,
          :url,
          :http_proxy_id,
          :user

        # ec2
        filter.permit :access_key,
          :region,
          :gov_cloud

        # gce
        filter.permit :email,
          :key_pair,
          :key_path,
          :project,
          :zone

        # libvirt
        filter.permit :display_type,
          :uuid

        # openstack
        filter.permit :allow_external_network,
          :key_pair,
          :tenant,
          :domain,
          :project_domain_name,
          :project_domain_id

        # ovirt
        filter.permit :datacenter,
          :ovirt_quota,
          :keyboard_layout,
          :use_v4,
          :public_key,
          :uuid

        # vmware
        filter.permit :datacenter,
          :pubkey_hash,
          :server,
          :uuid,
          :caching_enabled

        add_taxonomix_params_filter(filter)
      end
    end
  end

  def compute_resource_params
    self.class.compute_resource_params_filter.filter_params(params, parameter_filter_context)
  end
end

foreman/app/helpers/compute_resources_helper.rb
module ComputeResourcesHelper
  include LookupKeysHelper

  def vm_state(vm)
    if vm.state == 'PAUSED'
      ' ' + _("Paused")
    else
      vm.ready? ? _("On") : _("Off")
    end
  end

  def action_string(vm)
    vm.ready? ? ' ' + _("Off") : ' ' + _("On")
  end

  def vm_power_class(s)
    "class='label #{s ? 'label-success' : 'label-default'}'".html_safe
  end

  def vm_power_action(vm, authorizer = nil)
    opts = hash_for_power_compute_resource_vm_path(:compute_resource_id => @compute_resource, :id => vm.identity).merge(:auth_object => @compute_resource, :permission => 'power_compute_resources_vms', :authorizer => authorizer)
    html = power_action_html(vm)

    display_link_if_authorized "Power #{action_string(vm)}", opts, html.merge(:method => :put)
  end

  def power_action_html(vm)
    if vm.ready?
      {
        :data => { :confirm => _("Are you sure you want to power %{act} %{vm}?") % { :act => action_string(vm).downcase.strip, :vm => vm }},
        :class => "btn btn-danger",
      }
    else
      { :class => "btn btn-info" }
    end
  end

  def vm_pause_action(vm, authorizer = nil)
    opts = hash_for_pause_compute_resource_vm_path(:compute_resource_id => @compute_resource, :id => vm.identity).merge(:auth_object => @compute_resource, :permission => 'power_compute_resources_vms', :authorizer => authorizer)
    html = pause_action_html(vm)

    display_link_if_authorized pause_action_string(vm), opts, html.merge(:method => :put)
  end

  def pause_action_html(vm)
    pause_action = pause_action_string(vm).downcase
    if vm.state.downcase == 'paused'
      { :class => "btn btn-info" }
    else
      {
        :data => { :confirm => _("Are you sure you want to %{act} %{vm}?") % { :act => pause_action, :vm => vm } },
        :class => "btn btn-danger",
      }
    end
  end

  def pause_action_string(vm)
    vm.ready? ? _('Pause') : _('Resume')
  end

  def password_placeholder(obj, attr = nil)
    pass = obj.read_attribute(attr).present? || obj.read_attribute(:password_hash).present?
    pass ? "********" : ''
  end

  def list_datacenters(compute)
    return [] unless compute.uuid || controller.action_name == 'test_connection'
    compute.datacenters
  rescue Foreman::FingerprintException => e
    compute.errors.add(:pubkey_hash, e.message)
    []
  rescue Foreman::UsernameOrPasswordException => e
    Foreman::Logging.exception("Failed listing datacenters", e)
    compute.errors.add(:datacenter, e.message)
    []
  rescue => e
    Foreman::Logging.exception("Failed listing datacenters", e)
    []
  end

  def list_providers
    providers = ComputeResource.providers.map do |provider_name, provider_class|
      [provider_class.constantize.provider_friendly_name, provider_name]
    end
    providers.sort_by { |provider| provider.first }
  end

  def unset_password?
    action_name == "edit" || (action_name == "test_connection" && params[:cr_id].present?)
  end

  def test_connection_button_f(f, success, caption = nil)
    caption ||= _("Test Connection")
    btn_class = success ? 'btn-success' : 'btn-default'
    spinner_class = success ? 'spinner-inverse' : nil
    spinner_button_f(f, caption, "tfm.computeResource.testConnection(this)",
      :id => 'test_connection_button',
      :spinner_id => 'test_connection_indicator',
      :class => btn_class,
      :spinner_class => spinner_class,
      :'data-url' => test_connection_compute_resources_path)
  end

  def load_button_f(f, success, failure_caption)
    caption = success ? _("Test Connection") : failure_caption
    test_connection_button_f(f, success, caption)
  end

  def load_datacenters_button_f(f, success)
    load_button_f(f, success, _("Load Datacenters"))
  end

  def http_proxy_field(f)
    select_f(f, :http_proxy_id, HttpProxy.all, :id, :name,
      {:include_blank => true },
      { :label => _("HTTP Proxy") }
    )
  end
end

foreman/app/views/compute_resources/_form.html.erb
<%= form_for @compute_resource, :html => {:data => {:id => @compute_resource.try(:id)}} do |f| %>
  <%= base_errors_for @compute_resource %>
  <ul class="nav nav-tabs" data-tabs="tabs">
    <li class="active"><a href="#primary" data-toggle="tab"><%= _("Compute Resource") %></a></li>
    <% if show_location_tab? %>
      <li><a href="#locations" data-toggle="tab"><%= _("Locations") %></a></li>
    <% end %>
    <% if show_organization_tab? %>
      <li><a href="#organizations" data-toggle="tab"><%= _("Organizations") %></a></li>
    <% end %>
  </ul>

  <div class="tab-content">
    <div class="tab-pane active" id="primary">
      <%= text_f f, :name %>
      <%= f.hidden_field(:provider, :id => '') if f.object.uuid.present? %>
      <%= selectable_f f, :provider, list_providers, { :include_blank => _("Choose a provider")},
        {:label => _("Provider"), :disabled=> !f.object.new_record?, :'data-url'=> provider_selected_compute_resources_path, :onchange => 'tfm.computeResource.providerSelected(this);'} %>
      <%= textarea_f f, :description, :rows => 3 %>
      <div id='compute_connection'>
        <%= render "compute_resources/form/#{@compute_resource.provider.downcase}", :f => f unless @compute_resource.provider.empty? %>
      </div>
    </div>
    <%= render 'taxonomies/loc_org_tabs', :f => f, :obj => @compute_resource %>
  </div>

  <%= submit_or_cancel f %>
<% end %>

foreman/app/views/compute_resources/edit.html.erb
<% title _("Edit %s") % @compute_resource.name %>

<%= render 'form' %>

foreman/app/views/compute_resources/index.html.erb
<% title _("Compute Resources") %>
<% title_actions new_link(_("Create Compute Resource")),
                 documentation_button('5.2ComputeResources') %>

<table class="<%= table_css_classes 'table-fixed' %>">
  <thead>
    <tr>
      <th class="col-md-6"><%= sort :name, :as => s_("ComputeResource|Name") %></th>
      <th class="col-md-5"><%= sort :type, :as => _("Type") %></th>
      <th><%= _('Actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @compute_resources.each do |compute| %>
      <tr>
        <td class="ellipsis"><%= link_to compute.name, compute %></td>
        <td class="ellipsis"><%= compute.provider_friendly_name %></td>
        <td>
          <%= action_buttons(link_to_if_authorized(_('Edit'), hash_for_edit_compute_resource_path(compute).merge(:auth_object => compute, :authorizer => authorizer)),
                            display_delete_if_authorized(hash_for_compute_resource_path(:id => compute).merge(:auth_object => compute, :authorizer => authorizer), :data => { :confirm => _("Delete %s?") % compute.name })) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate_with_info @compute_resources %>

foreman/app/views/compute_resources/new.html.erb
<% title _("Create Compute Resource") %>

<%= render 'form' %>

foreman/app/views/compute_resources/show.html.erb
<% title @compute_resource.name %>

<% title_actions display_link_if_authorized(_("Associate VMs"),
                                            hash_for_associate_compute_resource_path(:compute_resource_id => @compute_resource).merge(:auth_object => @compute_resource, :permission => 'edit_compute_resources'),
                                            :title => _("Associate VMs to Foreman hosts"), :method => :put, :class=>"btn btn-default"),
(display_link_if_authorized(_('Refresh Cache'), hash_for_refresh_cache_compute_resource_path(@compute_resource).merge(:auth_object => @compute_resource, :permission => 'view_compute_resources'), :method => :put, :class => "btn btn-default") if @compute_resource.respond_to?(:refresh_cache) && @compute_resource.caching_enabled),
   link_to_if_authorized(_('Edit'), hash_for_edit_compute_resource_path(@compute_resource).merge(:auth_object => @compute_resource), :class => "btn btn-default")  %>

<ul class="nav nav-tabs" data-tabs="tabs">
  <li class="active"><a href="#primary" data-toggle="tab"><%= _("Compute Resource") %></a></li>
  <li><a href="#vms" data-toggle="tab"><%= _("Virtual Machines") %></a></li>
  <% if @compute_resource.capabilities.include?(:image) %>
    <li><a href="#images" data-toggle="tab"><%= _("Images") %></a></li>
  <% end %>
  <% if @compute_resource.capabilities.include?(:key_pair) %>
    <li><a href="#key_pairs" data-toggle="tab"><%= _("SSH keys") %></a></li>
  <% end %>
  <li><a href="#compute_profiles" data-toggle="tab"><%= _("Compute profiles") %></a></li>
  <%= render_tab_header_for(:main_tabs, :subject => @compute_resource) %>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="primary">
    <table class="<%= table_css_classes 'table-fixed' %>">
      <thead>
        <tr>
          <th class="col-md-1"><%= _('Property') %></th>
          <th class="col-md-11"><%= _('Value') %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= _("Provider") %></td>
          <td><%= @compute_resource.provider_friendly_name %></td>
        </tr>
        <% unless @compute_resource.description.empty? %>
          <tr>
            <td><%= _("Description") %></td>
            <td class="ellipsis"><%= @compute_resource.description %></td>
          </tr>
        <% end %>
        <%= render "compute_resources/show/#{@compute_resource.provider.downcase}" %>
      </tbody>
    </table>
  </div>
  <div id="vms" class="tab-pane" data-url=<%= compute_resource_vms_path(@compute_resource) %>>
    <%= spinner(_('Loading virtual machines information ...')) %>
  </div>
  <% if @compute_resource.capabilities.include?(:image) %>
    <div id="images" class="tab-pane">
      <%= title_actions(new_link(_("Create Image"), { :compute_resource_id => @compute_resource.id, :controller => :images }, { :data=>{:target=>"full-page"} })) %>
      <div id="images_list" data-url=<%= compute_resource_images_path(@compute_resource, { :partial => true }) %>>
        <%= spinner(_('Loading images information ...')) %>
      </div>
    </div>
  <% end %>
  <% if @compute_resource.capabilities.include?(:key_pair) %>
    <div id="key_pairs" class="tab-pane">
      <div id="key_pairs_list" data-url=<%= compute_resource_key_pairs_path(@compute_resource) %>>
        <%= spinner(_('Loading SSH keys information ...')) %>
      </div>
    </div>
  <% end %>
  <div id="compute_profiles" class="tab-pane">
    <table class="<%= table_css_classes 'table-fixed' %>">
      <thead>
        <tr>
          <th class="col-md-8"><%= _("Compute profile") %></th>
          <th><%= _("VM Attributes") %></th>
        </tr>
      </thead>
      <tbody>
        <% ComputeProfile.where(nil).each do |compute_profile| %>
          <% compute_attribute = ComputeAttribute.where(:compute_profile_id => compute_profile.id, :compute_resource_id => @compute_resource.id).first %>
          <% which_path = if compute_attribute.try(:id)
                            edit_compute_profile_compute_attribute_path(compute_profile.to_param, compute_attribute.id)
                          else
                            new_compute_profile_compute_resource_compute_attribute_path(compute_profile.to_param, @compute_resource.to_param)
                          end %>
          <tr>
            <td class="ellipsis"><%= link_to(compute_profile.name, which_path) %></td>
            <td>
              <% set = @compute_resource.compute_attributes.where(:compute_profile_id => compute_profile.id).first %>
              <%= set ? set.name : content_tag(:span, _("unspecified"), :class => 'gray') %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= render_tab_content_for(:main_tabs, :subject => @compute_resource) %>
</div>

foreman/app/views/compute_resources/welcome.html.erb
<% content_for(:title, _("Compute Resources")) %>
<% description = _("Foreman supports creating and managing hosts on a number of virtualization and cloud services - referred to as “compute resources” - as well as bare metal hosts.")%>
<% action = { :title => _("Create Compute Resource"), :url => new_compute_resource_path } if authorized_for(:action => :new)%>
<%= react_component('EmptyState', {
                                    :icon => 'cubes',
                                    :iconType => 'fa',
                                    :header => _('Compute Resources'),
                                    :description => description,
                                    :documentation => { :url => documentation_url("5.2ComputeResources") },
                                    :action => action
                                  }) %>