foreman/config/routes.rb
Foreman::Application.routes.draw do
  apipie_dsl
  resources :mail_notifications, only: [] do
    collection do
      get 'auto_complete_search'
    end
  end

  resources :config_reports, only: [:index, :show, :destroy] do
    collection do
      get 'auto_complete_search'
    end
  end

  welcoming_controllers = [
    'architectures',
    'auth_source_ldaps',
    'bookmarks',
    'common_parameters',
    'compute_profiles',
    'compute_resources',
    'config_reports',
    'domains',
    'fact_values',
    'hostgroups',
    'hosts',
    'http_proxies',
    'media',
    'models',
    'operatingsystems',
    'provisioning_templates',
    'ptables',
    'realms',
    'report_templates',
    'smart_proxies',
    'subnets',
    'usergroups',
  ]

  welcoming_controllers.each do |welcoming_controller|
    get "#{welcoming_controller}/help", action: :welcome, controller: welcoming_controller
  end

  constraints(id: /[^\/]+/) do
    resources :hosts do
      member do
        get 'clone'
        get 'review_before_build'
        put 'setBuild'
        get 'cancelBuild'
        get 'build_errors'
        get 'pxe_config'
        put 'toggle_manage'
        put 'power'
        get 'console'
        get 'overview'
        get 'bmc'
        get 'vm'
        get 'runtime'
        get 'resources'
        get 'templates'
        get 'nics'
        post 'forget_status'
        get 'statuses'
        put 'ipmi_boot'
        put 'disassociate'
      end
      collection do
        post 'multiple_actions'
        post 'multiple_parameters'
        post 'update_multiple_parameters'
        post 'select_multiple_hostgroup'
        post 'update_multiple_hostgroup'
        post 'select_multiple_owner'
        post 'update_multiple_owner'
        post 'select_multiple_power_state'
        post 'update_multiple_power_state'
        post 'select_multiple_puppet_ca_proxy'
        post 'update_multiple_puppet_ca_proxy'
        post 'multiple_destroy'
        post 'submit_multiple_destroy'
        post 'multiple_build'
        post 'submit_multiple_build'
        get 'reset_multiple'
        post 'multiple_disable'
        post 'submit_multiple_disable'
        post 'multiple_enable'
        post 'submit_multiple_enable'
        post 'multiple_disassociate'
        post 'update_multiple_disassociate'
        get 'auto_complete_search'
        post 'template_used'
        get 'active'
        get 'pending'
        get 'out_of_sync'
        get 'errors'
        get 'disabled'
        post 'current_parameters'
        post 'process_hostgroup'
        post 'process_taxonomy'
        post 'architecture_selected'
        post 'os_selected'
        post 'domain_selected'
        post 'use_image_selected'
        post 'compute_resource_selected'
        post 'scheduler_hint_selected'
        post 'interfaces'
        post 'medium_selected'
        post 'select_multiple_organization'
        post 'update_multiple_organization'
        post 'select_multiple_location'
        post 'update_multiple_location'
        post 'rebuild_config'
        post 'submit_rebuild_config'
        get 'random_name', only: :new
        get 'preview_host_collection'

        get 'register' => 'react#index'
        post 'register', to: 'registration_commands#create'
        get 'register/data', to: 'registration_commands#form_data'
        get 'register/os/:id', to: 'registration_commands#operatingsystem_template'
      end

      constraints(host_id: /[^\/]+/) do
        resources :config_reports, only: [:index, :show]
        resources :facts, only: :index, controller: :fact_values

        get 'parent_facts/*parent_fact/facts', to: 'fact_values#index', as: 'parent_fact_facts', parent_fact: /[\/\w.:_-]+/
      end
    end

    resources :bookmarks, except: [:show, :new, :create] do
      collection do
        get 'auto_complete_search'
      end
    end

    get 'parent_facts/:parent_fact/facts', to: 'fact_values#index', as: 'parent_fact_facts'
    resources :facts, only: [:index, :show] do
      constraints(id: /[^\/]+/) do
        resources :values, only: :index, controller: :fact_values, as: "host_fact_values"
      end
    end

    get 'unattended/template/:id/*hostgroup', to: "unattended#hostgroup_template", hostgroup: /.+/, format: 'text'
  end

  resources :settings, only: [:index, :update] do
    collection do
      get 'auto_complete_search'
    end
  end
  resources :common_parameters, except: [:show] do
    collection do
      get 'auto_complete_search'
    end
  end
  resources :parameters, only: [:index] do
    collection do
      get 'auto_complete_search'
    end
  end

  resources :compute_profiles do
    collection do
      get 'auto_complete_search'
    end
    resources :compute_attributes, only: [:create, :edit, :update]
    resources :compute_resources, only: [] do
      resources :compute_attributes, only: :new
    end
  end

  resources :hostgroups, except: [:show] do
    member do
      get 'nest'
      get 'clone'
    end
    collection do
      get 'auto_complete_search'
      post 'architecture_selected'
      post 'os_selected'
      post 'domain_selected'
      post 'use_image_selected'
      post 'medium_selected'
      post 'process_hostgroup'
    end
  end

  resources :smart_proxies do
    member do
      get 'ping'
      put 'refresh'
      get 'version'
      get 'plugin_version'
      get 'tftp_server'
      get 'log_pane'
      get 'failed_modules'
      get 'errors_card'
      get 'modules_card'
      post 'expire_logs'
    end
    constraints(id: /[^\/]+/) do
      resources :puppetca, only: [:index, :update, :destroy] do
        member do
          get 'counts'
          get 'expiry'
        end
      end
      resources :autosign, only: [:index, :new, :create, :destroy] do
        member do
          get 'counts'
        end
      end
    end
    collection do
      get 'auto_complete_search'
    end
  end

  resources :http_proxies, controller: 'http_proxies' do
    collection do
      get 'auto_complete_search'
      put 'test_connection'
    end
  end

  resources :fact_values, only: [:index] do
    collection do
      get 'auto_complete_search'
    end
  end

  resources :audits, only: [:index], constraints: ->(req) { req.format == :json }
  match '/audits/auto_complete_search' => 'audits#auto_complete_search', :via => [:get]
  match '/audits' => 'react#index', :via => [:get]

  resources :usergroups, except: [:show] do
    collection do
      get 'auto_complete_search'
    end
  end

  get 'menu', to: 'user_menus#menu'

  resources :users, except: [:show] do
    collection do
      get 'login'
      post 'login'
      get 'logout'
      post 'logout'
      get 'extlogin'
      get 'extlogout'
      get 'auto_complete_search'
      delete 'stop_impersonation'
    end
    member do
      post 'impersonate'
    end
    resources :ssh_keys, only: [:new, :create, :destroy]
  end
  resources :roles, except: [:show] do
    member do
      get 'clone'
      patch 'disable_filters_overriding'
    end
    collection do
      get 'auto_complete_search'
    end
  end

  resources :filters, except: [:show] do
    member do
      patch 'disable_overriding'
    end
    collection do
      get 'auto_complete_search'
    end
  end

  resources :permissions, only: [:index]

  resources :auth_source_ldaps, except: [:show, :index] do
    collection do
      put 'test_connection'
    end
  end

  resources :auth_sources, only: [:show, :index]
  resources :auth_source_externals, only: [:update, :edit]

  put 'users/(:id)/test_mail', to: 'users#test_mail', as: 'test_mail_user'

  constraints(id: /[^\/]+/) do
    resources :external_usergroups, except: [:index, :new, :create, :show, :edit, :update, :destroy] do
      member do
        put 'refresh'
      end
    end
  end

  scope 'templates' do
    resources :report_templates, except: [:show] do
      member do
        get 'clone_template'
        get 'lock'
        get 'unlock'
        get 'export'
        get 'generate'
        post 'schedule_report'
        post 'preview'
        get 'report_data'
      end
      collection do
        post 'preview'
        get 'revision'
        get 'auto_complete_search'
      end
    end
  end

  if SETTINGS[:unattended]
    resources :provisioning_templates, only: [] do
      collection do
        get 'build_pxe_default'
      end
    end

    scope 'templates' do
      resources :ptables, except: [:show] do
        member do
          get 'clone_template'
          get 'lock'
          get 'unlock'
          get 'export'
          post 'preview'
        end
        collection do
          post 'preview'
          get 'revision'
          get 'auto_complete_search'
        end
      end

      resources :provisioning_templates, except: [:show] do
        member do
          get 'clone_template'
          get 'lock'
          get 'unlock'
          get 'export'
          post 'preview'
        end
        collection do
          post 'preview'
          get 'revision'
          get 'auto_complete_search'
        end
      end
    end

    constraints(id: /[^\/]+/) do
      resources :domains, except: [:show] do
        collection do
          get 'auto_complete_search'
        end
      end

      resources :operatingsystems, except: [:show] do
        member do
          get 'bootfiles'
          get 'clone'
        end
        collection do
          get 'auto_complete_search'
        end
      end
    end
    resources :media, except: [:show] do
      collection do
        get 'auto_complete_search'
      end
    end

    resources :models, except: [:show, :index] do
      collection do
        get 'auto_complete_search'
      end
    end
    match 'models' => 'react#index', :via => :get

    resources :architectures, except: [:show] do
      collection do
        get 'auto_complete_search'
      end
    end

    constraints(id: /[^\/]+/) do
      resources :compute_resources do
        member do
          post 'template_selected'

foreman/app/controllers/api/v2/usergroups_controller.rb
module Api
  module V2
    class UsergroupsController < V2::BaseController
      include Foreman::Controller::Parameters::Usergroup

      before_action :find_optional_nested_object
      before_action :find_resource, :only => %w{show update destroy}

      api :GET, "/usergroups/", N_("List all user groups")
      param_group :search_and_pagination, ::Api::V2::BaseController
      add_scoped_search_description_for(Usergroup)

      def index
        @usergroups = resource_scope_for_index
      end

      api :GET, "/usergroups/:id/", N_("Show a user group")
      param :id, :identifier, :required => true

      def show
      end

      def_param_group :usergroup do
        param :usergroup, Hash, :required => true, :action_aware => true do
          param :name, String, :required => true
          param :admin, :bool, :required => false, :desc => N_("is an admin user group, can be modified by admins only")
          param :user_ids, Array, :require => false
          param :usergroup_ids, Array, :require => false
          param :role_ids, Array, :require => false
        end
      end

      api :POST, "/usergroups/", N_("Create a user group")
      param_group :usergroup, :as => :create

      def create
        @usergroup = Usergroup.new(usergroup_params)
        process_response @usergroup.save
      end

      api :PUT, "/usergroups/:id/", N_("Update a user group")
      description <<-DOC
        User groups linked to external groups (LDAP) are automatically synced
        with these groups on update. Remember this synchronization will remove
        any LDAP users manually added to the Foreman user group. Only LDAP
        users in the external groups will remain. Internal users can be added
        or removed freely.
      DOC
      param :id, String, :required => true
      param_group :usergroup

      def update
        process_response @usergroup.update(usergroup_params)
      end

      api :DELETE, "/usergroups/:id/", N_("Delete a user group")
      param :id, String, :required => true

      def destroy
        process_response @usergroup.destroy
      end

      rescue_from ::Foreman::CyclicGraphException do |error|
        @usergroup.errors.add :usergroups, error.message
        process_resource_error
      end

      private

      def allowed_nested_id
        %w(user_id usergroup_id)
      end
    end
  end
end

foreman/app/controllers/concerns/foreman/controller/parameters/usergroup.rb
module Foreman::Controller::Parameters::Usergroup
  extend ActiveSupport::Concern
  include Foreman::Controller::Parameters::ExternalUsergroup

  class_methods do
    def usergroup_params_filter
      Foreman::ParameterFilter.new(::Usergroup).tap do |filter|
        filter.permit :name,
          :external_usergroups_attributes => [external_usergroup_params_filter],
          :role_ids => [], :role_names => [],
          :user_ids => [], :user_names => [],
          :usergroup_ids => [], :usergroup_names => []

        filter.permit do |ctx|
          ctx.permit :admin if (User.current.try(:admin?) && ctx.ui?) || ctx.api?
        end
      end
    end
  end

  def usergroup_params
    self.class.usergroup_params_filter.filter_params(params, parameter_filter_context)
  end
end

foreman/app/controllers/usergroups_controller.rb
class UsergroupsController < ApplicationController
  include Foreman::Controller::AutoCompleteSearch
  include Foreman::Controller::Parameters::Usergroup
  include Foreman::Controller::ExternalUsergroupsErrors

  before_action :find_resource, :only => [:edit, :update, :destroy]
  before_action :get_external_usergroups_to_refresh, :only => [:update]

  def index
    @usergroups = resource_base_search_and_page(:usergroups)
  end

  def new
    @usergroup = Usergroup.new
  end

  def create
    @usergroup = Usergroup.new(usergroup_params)
    if @usergroup.save && refresh_external_usergroups
      process_success
    else
      process_error
    end
  rescue => e
    external_usergroups_error(@usergroup, e)
    process_error
  end

  def edit
  end

  def update
    if @usergroup.update(usergroup_params) &&
        refresh_external_usergroups
      process_success
    else
      process_error
    end
  rescue Foreman::CyclicGraphException => e
    @usergroup.errors[:usergroups] << e.record.errors[:base].join(' ')
    process_error
  rescue => e
    external_usergroups_error(@usergroup, e)
    process_error
  end

  def destroy
    if @usergroup.destroy
      process_success
    else
      process_error
    end
  end

  private

  def find_by_id(permission = :view_usergroups)
    Usergroup.authorized(permission).find(params[:id])
  end

  def get_external_usergroups_to_refresh
    # we need to load current status, so we call all explicitly
    @external_usergroups = @usergroup.external_usergroups.to_a
  end

  def external_usergroups
    @external_usergroups || []
  end

  def refresh_external_usergroups
    (external_usergroups + @usergroup.external_usergroups).uniq.map(&:refresh)
  end
end

foreman/app/views/usergroups/_external.html.erb
<div class='fields'>
  <div class="form-group">
    <%= field_set_tag _("External user group").html_safe + " #{remove_child_link('x', f, { :rel => 'twipsy', "data-title" => _('remove external user group'), :'data-placement' => 'left', :class => 'fr badge badge-danger'})}".html_safe, :id => 'external_usergroup' do %>
      <%= text_f f, :name %>
      <%= select_f f, :auth_source_id, AuthSource.non_internal, :id, :to_label %>
    <% end %>
  </div>
</div>

foreman/app/views/usergroups/_form.html.erb
<%= form_for @usergroup do |f| %>
  <%= base_errors_for @usergroup %>
  <ul class="nav nav-tabs" data-tabs="tabs">
    <li class="active"><a href="#primary" data-toggle="tab"><%= _("User Group") %></a></li>
    <li><a href="#roles" data-toggle="tab"><%= _("Roles") %></a></li>
    <% if AuthSource.non_internal.present? %>
      <li><a href="#external" data-toggle="tab"><%= _("External Groups") %></a></li>
    <% end %>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="primary">
      <% if @usergroup.external_usergroups.any? %>
        <h5>
          <%= _('Only internal (non-LDAP) users can be added manually. LDAP users
                are automatically synced from the External Groups list.') %>
        </h5>
        <h5>
          <%= _('To refresh the list of users, click on the tab "External
                groups" then "Refresh".') %>
        </h5>
        <hr>
      <% end %>
      <%= text_f f, :name %>
      <%= multiple_checkboxes f, :usergroups, @usergroup, Usergroup.except_current(@usergroup),
        { :label => _("User Groups") } %>
      <%= multiple_checkboxes f, :users, @usergroup, User.except_hidden,
        :label => _("Users"), :object_label_method => :select_title %>
    </div>
    <div class="tab-pane" id="roles">
      <%= checkbox_f f, :admin if User.current.can_change_admin_flag? %>
      <%= multiple_checkboxes f, :roles, @usergroup, Role.for_current_user, {:label => _('Roles')} %>
    </div>
    <% if AuthSource.non_internal.present? %>
      <div class="tab-pane" id="external">
        <table class="<%= table_css_classes('table-hover')%>">
          <thead>
            <tr>
              <th><%= s_("Usergroup|Name") %></th>
              <th><%= s_("Usergroup|Auth source") %></th>
              <th><%= _('Actions') %></th>
            </tr>
          </thead>
          <tbody><% @usergroup.external_usergroups.each do |usergroup| %>
              <tr>
                <% next if usergroup.id.nil? %>
                <td><%= h usergroup.name %></td>
                <td><%= h usergroup.auth_source %></td>
                <td><%= display_link_if_authorized(_('Refresh'),
                                                         hash_for_refresh_external_usergroup_path(:id => usergroup),
                                                         :method => :put, :id => usergroup.id,
                                                         :class => "btn btn-default", :title => usergroup.supports_refresh? ? _('Synchronize group from authentication source') : _("Synchronization is not available for #{usergroup.auth_source.name} auth source"),
                                                         :disabled => !usergroup.supports_refresh?) %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <button class='btn btn-info' type='button'
          onclick="$('#current_external_usergroups').toggle();"><%= _("Show linked external user groups") %></button>
        <hr>
        <% invalid_external_groups = @usergroup.external_usergroups.any? { |e| e.errors.present? } %>
        <div style='<%= invalid_external_groups ? '' : 'display:none' %>' id='current_external_usergroups'>
          <%= f.fields_for :external_usergroups do |ug| %>
            <%= render 'external', :f => ug %>
          <% end %>
          <hr>
        </div>
        <div class="children_fields">
          <%= new_child_fields_template(f, :external_usergroups, { :partial => 'external' } ) %>
          <%= add_child_link '+ ' + _('Add external user group'), :external_usergroups, { :class => "info", :title => _('link external user group with this user group') } %>
        </div>
      </div>
    <% end %>
  </div>
  <%= submit_or_cancel f %>
<% end %>

foreman/app/views/usergroups/edit.html.erb
<% title _("Edit %s") % @usergroup.to_label %>

<%= render :partial => 'form' %>

foreman/app/views/usergroups/index.html.erb
<% title _("User Groups") %>

<% title_actions new_link(_("Create User Group")) %>

<table class="<%= table_css_classes 'table-fixed' %>">
  <thead>
    <tr>
      <th class="col-md-4"><%= sort :name, :as => s_("Usergroup|Name") %></th>
      <th class="col-md-4"><%= _("Users") %></th>
      <th class="col-md-3"><%= _("User Groups") %></th>
      <th><%= _('Actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @usergroups.each do |usergroup| %>
      <tr>
        <td class="ellipsis"><%= link_to_if_authorized trunc_with_tooltip(usergroup.name), hash_for_edit_usergroup_path(:id => usergroup.id).merge(:auth_object => usergroup, :authorizer => authorizer) %></td>
        <td class="ellipsis"><%= usergroup.users.except_hidden.map(&:login).to_sentence %></td>
        <td class="ellipsis"><%= usergroup.usergroups.map(&:name).to_sentence %></td>
        <td>
          <%= action_buttons(display_delete_if_authorized(
            hash_for_usergroup_path(:id => usergroup).
            merge(:auth_object => usergroup, :authorizer => authorizer),
            :data => { :confirm => (_("Delete %s?") % usergroup.name) } )) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate_with_info @usergroups %>

foreman/app/views/usergroups/new.html.erb
<% title _("Create User group") %>

<%= render :partial => 'form' %>

foreman/app/views/usergroups/welcome.html.erb
<% content_for(:title, _("User Groups")) %>
<% description =
_("With user groups, you can group your users and assign them roles on a group basis.
 User groups enable users to log into Foreman and be automatically granted permissions.
 A Foreman user group can be associated to a group stored in an LDAP server, so membership of the LDAP group automatically adds the user to the Foreman user group.")
%>
<% action = { :title => _("Create User group"), :url => new_usergroup_path } if authorized_for(:action => :new)%>
<%= react_component('EmptyState', {
                                    :icon => 'project',
                                    :iconType => 'pf',
                                    :header => _('User Groups'),
                                    :description => description,
                                    :action => action
                                  }) %>