foreman/config/routes.rb
Foreman::Application.routes.draw do
  apipie_dsl
  resources :mail_notifications, only: [] do
    collection do
      get 'auto_complete_search'
    end
  end

  resources :config_reports, only: [:index, :show, :destroy] do
    collection do
      get 'auto_complete_search'
    end
  end

  welcoming_controllers = [
    'architectures',
    'auth_source_ldaps',
    'bookmarks',
    'common_parameters',
    'compute_profiles',
    'compute_resources',
    'config_reports',
    'domains',
    'fact_values',
    'hostgroups',
    'hosts',
    'http_proxies',
    'media',
    'models',
    'operatingsystems',
    'provisioning_templates',
    'ptables',
    'realms',
    'report_templates',
    'smart_proxies',
    'subnets',
    'usergroups',
  ]

  welcoming_controllers.each do |welcoming_controller|
    get "#{welcoming_controller}/help", action: :welcome, controller: welcoming_controller
  end

  constraints(id: /[^\/]+/) do
    resources :hosts do
      member do
        get 'clone'
        get 'review_before_build'
        put 'setBuild'
        get 'cancelBuild'
        get 'build_errors'
        get 'pxe_config'
        put 'toggle_manage'
        put 'power'
        get 'console'
        get 'overview'
        get 'bmc'
        get 'vm'
        get 'runtime'
        get 'resources'
        get 'templates'
        get 'nics'
        post 'forget_status'
        get 'statuses'
        put 'ipmi_boot'
        put 'disassociate'
      end
      collection do
        post 'multiple_actions'
        post 'multiple_parameters'
        post 'update_multiple_parameters'
        post 'select_multiple_hostgroup'
        post 'update_multiple_hostgroup'
        post 'select_multiple_owner'
        post 'update_multiple_owner'
        post 'select_multiple_power_state'
        post 'update_multiple_power_state'
        post 'select_multiple_puppet_ca_proxy'
        post 'update_multiple_puppet_ca_proxy'
        post 'multiple_destroy'
        post 'submit_multiple_destroy'
        post 'multiple_build'
        post 'submit_multiple_build'
        get 'reset_multiple'
        post 'multiple_disable'
        post 'submit_multiple_disable'
        post 'multiple_enable'
        post 'submit_multiple_enable'
        post 'multiple_disassociate'
        post 'update_multiple_disassociate'
        get 'auto_complete_search'
        post 'template_used'
        get 'active'
        get 'pending'
        get 'out_of_sync'
        get 'errors'
        get 'disabled'
        post 'current_parameters'
        post 'process_hostgroup'
        post 'process_taxonomy'
        post 'architecture_selected'
        post 'os_selected'
        post 'domain_selected'
        post 'use_image_selected'
        post 'compute_resource_selected'
        post 'scheduler_hint_selected'
        post 'interfaces'
        post 'medium_selected'
        post 'select_multiple_organization'
        post 'update_multiple_organization'
        post 'select_multiple_location'
        post 'update_multiple_location'
        post 'rebuild_config'
        post 'submit_rebuild_config'
        get 'random_name', only: :new
        get 'preview_host_collection'

        get 'register' => 'react#index'
        post 'register', to: 'registration_commands#create'
        get 'register/data', to: 'registration_commands#form_data'
        get 'register/os/:id', to: 'registration_commands#operatingsystem_template'
      end

      constraints(host_id: /[^\/]+/) do
        resources :config_reports, only: [:index, :show]
        resources :facts, only: :index, controller: :fact_values

        get 'parent_facts/*parent_fact/facts', to: 'fact_values#index', as: 'parent_fact_facts', parent_fact: /[\/\w.:_-]+/
      end
    end

    resources :bookmarks, except: [:show, :new, :create] do
      collection do
        get 'auto_complete_search'
      end
    end

    get 'parent_facts/:parent_fact/facts', to: 'fact_values#index', as: 'parent_fact_facts'
    resources :facts, only: [:index, :show] do
      constraints(id: /[^\/]+/) do
        resources :values, only: :index, controller: :fact_values, as: "host_fact_values"
      end
    end

    get 'unattended/template/:id/*hostgroup', to: "unattended#hostgroup_template", hostgroup: /.+/, format: 'text'
  end

  resources :settings, only: [:index, :update] do
    collection do
      get 'auto_complete_search'
    end
  end
  resources :common_parameters, except: [:show] do
    collection do
      get 'auto_complete_search'
    end
  end
  resources :parameters, only: [:index] do
    collection do
      get 'auto_complete_search'
    end
  end

  resources :compute_profiles do
    collection do
      get 'auto_complete_search'
    end
    resources :compute_attributes, only: [:create, :edit, :update]
    resources :compute_resources, only: [] do
      resources :compute_attributes, only: :new
    end
  end

  resources :hostgroups, except: [:show] do
    member do
      get 'nest'
      get 'clone'
    end
    collection do
      get 'auto_complete_search'
      post 'architecture_selected'
      post 'os_selected'
      post 'domain_selected'
      post 'use_image_selected'
      post 'medium_selected'
      post 'process_hostgroup'
    end
  end

  resources :smart_proxies do
    member do
      get 'ping'
      put 'refresh'
      get 'version'
      get 'plugin_version'
      get 'tftp_server'
      get 'log_pane'
      get 'failed_modules'
      get 'errors_card'
      get 'modules_card'
      post 'expire_logs'
    end
    constraints(id: /[^\/]+/) do
      resources :puppetca, only: [:index, :update, :destroy] do
        member do
          get 'counts'
          get 'expiry'
        end
      end
      resources :autosign, only: [:index, :new, :create, :destroy] do
        member do
          get 'counts'
        end
      end
    end
    collection do
      get 'auto_complete_search'
    end
  end

  resources :http_proxies, controller: 'http_proxies' do
    collection do
      get 'auto_complete_search'
      put 'test_connection'
    end
  end

  resources :fact_values, only: [:index] do
    collection do
      get 'auto_complete_search'
    end
  end

  resources :audits, only: [:index], constraints: ->(req) { req.format == :json }
  match '/audits/auto_complete_search' => 'audits#auto_complete_search', :via => [:get]
  match '/audits' => 'react#index', :via => [:get]

  resources :usergroups, except: [:show] do
    collection do
      get 'auto_complete_search'
    end
  end

  get 'menu', to: 'user_menus#menu'

  resources :users, except: [:show] do
    collection do
      get 'login'
      post 'login'
      get 'logout'
      post 'logout'
      get 'extlogin'
      get 'extlogout'
      get 'auto_complete_search'
      delete 'stop_impersonation'
    end
    member do
      post 'impersonate'
    end
    resources :ssh_keys, only: [:new, :create, :destroy]
  end
  resources :roles, except: [:show] do
    member do
      get 'clone'
      patch 'disable_filters_overriding'
    end
    collection do
      get 'auto_complete_search'
    end
  end

  resources :filters, except: [:show] do
    member do
      patch 'disable_overriding'
    end
    collection do
      get 'auto_complete_search'
    end
  end

  resources :permissions, only: [:index]

  resources :auth_source_ldaps, except: [:show, :index] do
    collection do
      put 'test_connection'
    end
  end

  resources :auth_sources, only: [:show, :index]
  resources :auth_source_externals, only: [:update, :edit]

  put 'users/(:id)/test_mail', to: 'users#test_mail', as: 'test_mail_user'

  constraints(id: /[^\/]+/) do
    resources :external_usergroups, except: [:index, :new, :create, :show, :edit, :update, :destroy] do
      member do
        put 'refresh'
      end
    end
  end

  scope 'templates' do
    resources :report_templates, except: [:show] do
      member do
        get 'clone_template'
        get 'lock'
        get 'unlock'
        get 'export'
        get 'generate'
        post 'schedule_report'
        post 'preview'
        get 'report_data'
      end
      collection do
        post 'preview'
        get 'revision'
        get 'auto_complete_search'
      end
    end
  end

  if SETTINGS[:unattended]
    resources :provisioning_templates, only: [] do
      collection do
        get 'build_pxe_default'
      end
    end

    scope 'templates' do
      resources :ptables, except: [:show] do
        member do
          get 'clone_template'
          get 'lock'
          get 'unlock'
          get 'export'
          post 'preview'
        end
        collection do
          post 'preview'
          get 'revision'
          get 'auto_complete_search'
        end
      end

      resources :provisioning_templates, except: [:show] do
        member do
          get 'clone_template'
          get 'lock'
          get 'unlock'
          get 'export'
          post 'preview'
        end
        collection do
          post 'preview'
          get 'revision'
          get 'auto_complete_search'
        end
      end
    end

    constraints(id: /[^\/]+/) do
      resources :domains, except: [:show] do
        collection do
          get 'auto_complete_search'
        end
      end

      resources :operatingsystems, except: [:show] do
        member do
          get 'bootfiles'
          get 'clone'
        end
        collection do
          get 'auto_complete_search'
        end
      end
    end
    resources :media, except: [:show] do
      collection do
        get 'auto_complete_search'
      end
    end

    resources :models, except: [:show, :index] do
      collection do
        get 'auto_complete_search'
      end
    end
    match 'models' => 'react#index', :via => :get

    resources :architectures, except: [:show] do
      collection do
        get 'auto_complete_search'
      end
    end

    constraints(id: /[^\/]+/) do
      resources :compute_resources do
        member do
          post 'template_selected'

foreman/app/controllers/concerns/foreman/controller/parameters/provisioning_template.rb
module Foreman::Controller::Parameters::ProvisioningTemplate
  extend ActiveSupport::Concern
  include Foreman::Controller::Parameters::Taxonomix
  include Foreman::Controller::Parameters::Template
  include Foreman::Controller::Parameters::TemplateCombination

  class_methods do
    def provisioning_template_params_filter
      Foreman::ParameterFilter.new(::ProvisioningTemplate).tap do |filter|
        filter.permit :template_combinations_attributes => [template_combination_params_filter],
          :operatingsystems => [], :operatingsystem_ids => [], :operatingsystem_names => []
        add_taxonomix_params_filter(filter)
        add_template_params_filter(filter)
      end
    end
  end

  def provisioning_template_params
    self.class.provisioning_template_params_filter.filter_params(params, parameter_filter_context)
  end

  def organization_params
    self.class.organization_params_filter(::ProvisioningTemplate).filter_params(params, parameter_filter_context)
  end

  def location_params
    self.class.location_params_filter(::ProvisioningTemplate).filter_params(params, parameter_filter_context)
  end
end

foreman/app/controllers/concerns/foreman/controller/provisioning_templates.rb
module Foreman::Controller::ProvisioningTemplates
  extend ActiveSupport::Concern

  def load_vars_from_template
    return unless @template

    @locations        = @template.locations
    @organizations    = @template.organizations
    @template_kind_id = @template.template_kind_id
    @operatingsystems = @template.operatingsystems if @template.respond_to?(:operatingsystems)
  end

  private

  def default_template_url(template, hostgroup)
    uri      = URI.parse(Setting[:unattended_url])
    host     = uri.host
    port     = uri.port
    protocol = uri.scheme

    url_for(:only_path => false, :action => :hostgroup_template, :controller => '/unattended',
            :id => template.name, :hostgroup => hostgroup.title, :protocol => protocol,
            :host => host, :port => port)
  end

  # convert the file upload into a simple string to save in our db.
  def handle_template_upload
    return unless params[type_name_singular] && (template = params[type_name_singular][:template])
    params[type_name_singular][:template] = template.read if template.respond_to?(:read)
  end

  def process_template_kind
    return unless params[type_name_singular] && (template_kind = params[type_name_singular].delete(:template_kind))
    params[type_name_singular][:template_kind_id] = template_kind[:id]
  end

  def type_name_singular
    @type_name_singular ||= resource_class.to_s.underscore
  end
end

foreman/app/controllers/provisioning_templates_controller.rb
class ProvisioningTemplatesController < TemplatesController
  include Foreman::Controller::Parameters::ProvisioningTemplate
  helper_method :documentation_anchor

  def build_pxe_default
    status, msg = ProvisioningTemplate.authorized(:deploy_provisioning_templates).build_pxe_default
    (status == :ok) ? success(msg) : error(msg)
    redirect_back(fallback_location: provisioning_templates_path)
  end

  def documentation_anchor
    '4.4.3ProvisioningTemplates'
  end
end

foreman/app/helpers/provisioning_templates_helper.rb
module ProvisioningTemplatesHelper
  def combination(template)
    template.template_combinations.map { |comb| comb.hostgroup.to_s }.to_sentence
  end

  def template_kind(template)
    template.template_kind
  end

  def permitted_actions(template)
    actions = [
      display_link_if_authorized(_('Clone'), template_hash_for_member(template, 'clone_template')),
      display_link_if_authorized(_('Export'), template_hash_for_member(template, 'export'), { :data => { :no_turbolink => true } }),
    ]

    if template.is_a?(ReportTemplate) && !template.snippet
      actions.unshift(display_link_if_authorized(_('Generate'), template_hash_for_member(template, 'generate').merge(:authorizer => authorizer, :auth_object => template), { :data => { :no_turbolink => true } }))
    end

    if template.locked?
      confirm = [
        _("You are about to unlock a locked template."),
        _("This is for every location and organization that uses it."),
        if template.vendor
          _("It is not recommended to unlock this template, as it is provided by %{vendor} and may be overwritten. Please consider cloning it instead.") %
            {:vendor => template.vendor}
        end,

        _("Continue?"),
      ].compact

      actions << display_link_if_authorized(_('Unlock'), template_hash_for_member(template, 'unlock'),
        {:data => {:confirm => confirm.join(" ")}, :style => 'color: red'})

    else
      actions << display_link_if_authorized(_('Lock'), template_hash_for_member(template, 'lock'))
      actions << display_delete_if_authorized(template_hash_for_member(template).
         merge(:auth_object => template, :authorizer => authorizer, :permission => "destroy_#{@type_name_plural}"),
        :data => {:confirm => _("Delete %s?") % template})
    end
  end

  def pxe_with_building_hosts?(template)
    kinds = ["PXELinux", "PXEGrub"]
    template.respond_to?(:template_kind) &&
      template.respond_to?(:operatingsystem_ids) &&
      template.template_kind.present? &&
      kinds.include?(template.template_kind.name) &&
      building_hosts(template).any?
  end

  def building_hosts(template)
    Host.where(:build => true, :operatingsystem_id => template.operatingsystem_ids)
  end

  def building_hosts_path(template)
    oses = template.operatingsystem_ids.map { |id| "os_id = #{id}" }.join(" or ")
    hosts_path(:search => "build = true and ( #{oses} )")
  end

  def how_templates_are_determined
    alert(:class => 'alert-info', :header => _('How templates are determined'),
          :text => ('<p>' + _("When editing a template, you must assign a list \
of operating systems which this template can be used with. Optionally, you can \
restrict a template to a list of host groups.") + '</p>' +
'<p>' + _("When a Host requests a template (e.g. during provisioning), Foreman \
will select the best match from the available templates of that type, in the \
following order:") + '</p>' + '<ul>' +
    '<li>' + _("Host group") + '</li>' +
    '<li>' + _("Operating system default") + '</li>' +
    '</ul>' +
    (_("The final entry, Operating System default, can be set by editing the %s page.") %
     (link_to _("Operating System"), operatingsystems_path))).html_safe)
  end
end

foreman/app/views/unattended/provisioning_templates/snippet/ansible_tower_callback_service.erb
<%#
kind: snippet
name: ansible_tower_callback_service
model: ProvisioningTemplate
snippet: true
-%>
[Unit]
Description=Provisioning callback to Ansible Tower
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/bin/curl -k -s --data "host_config_key=<%= host_param('ansible_host_config_key') -%>" https://<%= host_param('ansible_tower_fqdn') -%>/api/v2/job_templates/<%= host_param('ansible_job_template_id') -%>/callback/
ExecStartPost=/usr/bin/systemctl disable ansible-callback

[Install]
WantedBy=multi-user.target

foreman/app/views/unattended/provisioning_templates/snippet/blacklist_kernel_modules.erb
<%#
kind: snippet
name: blacklist_kernel_modules
model: ProvisioningTemplate
snippet: true
-%>
<% if host_param('blacklist_kernel_modules') -%>
<% host_param('blacklist_kernel_modules').split.each do |mod| -%>
echo "blacklist <%= mod %>" >> /etc/modprobe.d/blacklist.conf
<% end -%>
<% end -%>

foreman/app/views/unattended/provisioning_templates/snippet/built.erb
<%#
kind: snippet
name: built
model: ProvisioningTemplate
snippet: true
-%>
<%#
  Sends 'built' request to exit build mode. Only use in multi-line shell context.
  Tries curl, if not found then wget and finally wget from busybox (limited options).
-%>
<%
  endpoint = @endpoint || 'built'
  method = @method || 'POST'
  url = foreman_url(endpoint)
  curl_opts = ["-H 'Content-Type: text/plain'"]
  wget_opts = ["--header 'Content-Type: text/plain'"]
  if url.start_with?('https')
    curl_opts << "--insecure"
    wget_opts << "--no-check-certificate"
  end
  if @body_file
    curl_opts << "--data @#{@body_file}"
    wget_opts << "--body-file=#{@body_file}"
  end
-%>
if [ -x /usr/bin/curl ]; then
  /usr/bin/curl -o /dev/null --noproxy \* <%= curl_opts.join(' ') %> --silent '<%= url %>'
elif [ -x /usr/bin/wget ]; then
  /usr/bin/wget -q -O /dev/null --no-proxy --method <%= method %> <%= wget_opts.join(' ') %> '<%= url %>'
else
  wget -q -O /dev/null --header 'Content-Type: text/plain' '<%= url %>'
fi

foreman/app/views/unattended/provisioning_templates/snippet/chef_client.erb
<%#
kind: snippet
name: chef_client
model: ProvisioningTemplate
snippet: true
description: this is a single entry point for chef-client bootstrapping, it selects
    a bootstrapping strategy based on host parameter named "chef_bootstrap_template"
    note that it can be set per hostgroup, os, domain etc.
    if there's no strategy set, omnibus is used by default
%>
echo "Bootstraping chef"
<%= snippet_if_exists(host_param('chef_bootstrap_template') || 'chef-client omnibus bootstrap') %>

foreman/app/views/unattended/provisioning_templates/snippet/coreos_cloudconfig.erb
#cloud-config
<%#
kind: snippet
name: coreos_cloudconfig
model: ProvisioningTemplate
snippet: true
%>
<%
  units = 0
  unless host_param_false?('enable_etcd')
    units += 1
  end
  if host_param_true?('expose_docker_socket')
    units += 1
  end
  if @host.subnet.respond_to?(:dhcp_boot_mode?)
    dhcp = @host.subnet.dhcp_boot_mode? && !@static
  else
    dhcp = !@static
  end
  unless dhcp
    units += 1
  end
-%>
<% if units > 0 -%>
      coreos:
<% if host_param('reboot-strategy') -%>
        update:
          reboot-strategy: <%= host_param('reboot-strategy') %>
<% end -%>
<% unless host_param_false?('enable_etcd') -%>
        etcd2:
<% if host_param('etcd_discovery_url') -%>
          discovery: <%= host_param('etcd_discovery_url') %>
<% end -%>
          advertise-client-urls: http://<%= @host.ip %>:2379
          initial-advertise-peer-urls: http://<%= @host.ip %>:2380
          listen-client-urls: http://0.0.0.0:2379
          listen-peer-urls: http://0.0.0.0:2380
<% end -%>
        units:
<% unless host_param_false?('enable_etcd') -%>
          - name: etcd2.service
            command: start
          - name: fleet.service
            command: start
<% end -%>
<% if host_param_true?('expose_docker_socket') -%>
          - name: docker-tcp.socket
            command: start
            enable: yes
            content: |
              [Unit]
              Description=Docker Socket for the API

              [Socket]
              ListenStream=2375
              BindIPv6Only=both
              Service=docker.service

              [Install]
              WantedBy=sockets.target
          - name: enable-docker-tcp.service
            command: start
            content: |
              [Unit]
              Description=Enable the Docker Socket for the API

              [Service]
              Type=oneshot
              ExecStart=/usr/bin/systemctl enable docker-tcp.socket
<% end -%>
<% unless dhcp -%>
          - name: systemd-networkd.service
            command: stop
          - name: static.network
            command: start
            content: |
              [Match]
              MACAddress=<%= @host.mac %>
              [Network]
<% if @host.subnet.present? -%>
              Gateway=<%= @host.subnet.gateway %>
<% end -%>
              Address=<%= @host.ip %>/<%= @host.subnet.cidr %>
<% @host.subnet.dns_servers.each do |nameserver| -%>
              DNS=<%= nameserver %>
<% end -%>
          - name: down-interfaces.service
            command: start
            content: |
              [Service]
              Type=oneshot
              ExecStart=/usr/bin/bash -c 'for i in $(/usr/bin/ls /sys/class/net/); do [ $i == "lo" ] || (/usr/bin/ip link set $i down; /usr/bin/ip addr flush dev $i); done'
          - name: systemd-networkd.service
            command: restart
<% end -%>
<% end -%>
      hostname: <%= @host.name %>
<% if host_param('ssh_authorized_keys') -%>
      ssh_authorized_keys:
  <% host_param('ssh_authorized_keys').split(',').map{ |item| item.strip }.each do |ssh_key| -%>
      - "<%= ssh_key %>"
  <% end -%>
<% else -%>
      users:
        - name: core
          passwd: <%= root_pass %>
<% end -%>

foreman/app/views/unattended/provisioning_templates/snippet/efibootmgr_netboot.erb
<%#
kind: snippet
name: efibootmgr_netboot
model: ProvisioningTemplate
description: Configure booting from network in EFI
snippet: true
%>
<% if host_param('efi_bootentry') == 'previous' -%>
if [ -d /sys/firmware/efi ]; then
  echo "Changing EFI boot order to preserve boot. Typically the previous entry"
  echo "was network boot in netboot workflows but this can also break things."
  echo "In that case use efi_keep_bootorder host parameter to keep it untouched."
  echo "Boot order is currently:"
  efibootmgr
  echo
  created_entry=$(efibootmgr | grep "BootOrder" | cut -d " " -f 2 | cut -d "," -f 1)
  others=$(efibootmgr | grep "BootOrder" | cut -d " " -f 2 | cut -d "," -f 2-)
  new_order="${others},${created_entry}"
  echo "Found entry ${created_entry}, changing order to:"
  efibootmgr -o ${new_order}
  echo
fi
<% elsif (entry = host_param('efi_bootentry')) -%>
if [ -d /sys/firmware/efi ]; then
  echo "Trying to find EFI boot entry containing: <%= entry -%>"
  echo "Boot order is currently:"
  efibootmgr
  echo
  current=$(efibootmgr | grep "BootOrder" | cut -d " " -f 2)
  id=$(efibootmgr | grep -E '^Boot[0-9]+' | grep -E 'a' | efibootmgr | grep -E '^Boot[0-9]+' | grep -E '<%= entry -%>' | cut -c5-8)
  echo "Found entry ${id}, changing order to:"
  efibootmgr -o ${id},${current}
  echo
fi
<% end -%>

foreman/app/views/unattended/provisioning_templates/snippet/fips_packages.erb
<%#
kind: snippet
name: fips_packages
model: ProvisioningTemplate
snippet: true
%>
dracut-fips
-prelink

foreman/app/views/unattended/provisioning_templates/snippet/http_proxy.erb
<%#
kind: snippet
name: http_proxy
model: ProvisioningTemplate
snippet: true
%>
<% if (proxy = host_param("http_proxy")) -%>
http_proxy=<%= proxy %>
export http_proxy
https_proxy=<%= proxy %>
export https_proxy
no_proxy=localhost,127.0.0.0/8,*.local,*.<%= @host.domain.name -%>,puppet
export no_proxy
<% end -%>

foreman/app/views/unattended/provisioning_templates/snippet/insights.erb
<%#
kind: snippet
name: insights
model: ProvisioningTemplate
snippet: true
%>
<% if @host.operatingsystem.name == 'RedHat' -%>
echo '#'
echo '# Installing Insights client'
echo '#'

yum install -y insights-client
insights-client --test-connection
insights-client --register

<% end -%>

foreman/app/views/unattended/provisioning_templates/snippet/remote_execution_ssh_keys.erb
<%#
kind: snippet
name: remote_execution_ssh_keys
model: ProvisioningTemplate
snippet: true
%>
# SSH keys setup snippet for Remote Execution plugin
#
# Parameters:
#
# remote_execution_ssh_keys: public keys to be put in ~/.ssh/authorized_keys
#
# remote_execution_ssh_user: user for which remote_execution_ssh_keys will be
#                            authorized
#
# remote_execution_create_user: create user if it not already existing
#
# remote_execution_effective_user_method: method to switch from ssh user to
#                                         effective user
#
# This template sets up SSH keys in any host so that as long as your public
# SSH key is in remote_execution_ssh_keys, you can SSH into a host. This
# works in combination with Remote Execution plugin by querying smart proxies
# to build an array.
#
# To use this snippet without the plugin provide the SSH keys as host parameter
# remote_execution_ssh_keys. It expects the same format like the authorized_keys
# file.


<% if !host_param('remote_execution_ssh_keys').blank? %>
<% ssh_user = host_param('remote_execution_ssh_user') || 'root' %>

user_exists=false
getent passwd <%= ssh_user %> >/dev/null 2>&1 && user_exists=true

<% if ssh_user != 'root' && host_param_true?('remote_execution_create_user') -%>
if ! $user_exists; then
  useradd -m <%= ssh_user %> && user_exists=true
fi
<% end -%>

if $user_exists; then
<% ssh_path = "~#{ssh_user}/.ssh" %>

  mkdir -p <%= ssh_path %>

  cat << EOF >> <%= ssh_path %>/authorized_keys
<%= host_param('remote_execution_ssh_keys').is_a?(String) ? host_param('remote_execution_ssh_keys') : host_param('remote_execution_ssh_keys').join("\n") %>
EOF

  chmod 0700 <%= ssh_path %>
  chmod 0600 <%= ssh_path %>/authorized_keys
  chown -R <%= "#{ssh_user}:" %> <%= ssh_path %>

  # Restore SELinux context with restorecon, if it's available:
  command -v restorecon && restorecon -RvF <%= ssh_path %> || true

<% if ssh_user != 'root' && host_param('remote_execution_effective_user_method') == 'sudo' -%>
<% if @host.operatingsystem.family == 'Redhat' || @host.operatingsystem.family == 'Debian' -%>
echo "<%= ssh_user %> ALL = (root) NOPASSWD : ALL
Defaults:<%= ssh_user %> !requiretty" > /etc/sudoers.d/<%= ssh_user %>
<% elsif @host.operatingsystem.family == 'Suse' -%>
echo "<%= ssh_user %> ALL = (root) NOPASSWD : ALL
Defaults:<%= ssh_user %> !targetpw" >> /etc/sudoers
<% end -%>
<% end -%>
else
  echo 'The remote_execution_ssh_user does not exist and remote_execution_create_user is not set to true.  remote_execution_ssh_keys snippet will not install keys'
fi
<% end -%>